apiVersion: v1
kind: Namespace
metadata:
  name: github-explorer
  labels:
    app: github-explorer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: github-explorer
  labels:
    app: github-explorer
    tier: frontend
spec:
  selector:
    app: github-explorer
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: github-explorer
  labels:
    app: github-explorer
    tier: frontend
spec:
  selector:
    matchLabels:
      app: github-explorer
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: github-explorer
        tier: frontend
    spec:
      containers:
        - name: github-explorer
          image: mmontes11/github-explorer:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
